apiVersion: v1
kind: List
items:
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: simple-notebook
      labels:
        app.openshift.io/runtime: python
        svc: simple-notebook
        app: jupyterhub
    spec:
      runPolicy: Serial
      source:
        git:
          ref: develop
          uri: "https://github.com/txsvc/jupyter-notebooks"
        contextDir: "examples/simple-notebook"
        type: Git
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: "python:3.9-ubi8"
            namespace: openshift
          env:
            - name: NOTEBOOK_VERSION
              value: "6.4.11"
      output:
        to:
          kind: ImageStreamTag
          name: simple-notebook:latest
      triggers:
        - type: ImageChange
          imageChange: {}
        - type: ConfigChange

  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      name: simple-notebook
      labels:
        app.openshift.io/runtime: python
        svc: simple-notebook
        app: jupyterhub
      annotations:
        description: simple-notebook image
